analytics: {}
color:
  brandColors:
    - '#606467'
    - '#FDFDFD'
    - '#A0A788'
    - '#A11806'
    - '#55C400'
  brandStrength: 0.641728
  lightness: 0.84375
  rhythmicContrast: 0.947802
  saturation: 0.856338
cta: {}
layout_spectrum: 0.9121850111987442
name: Daffyd75
opengraph: {}
purpose: []
typography_spectrum: 0.1823249540757388
